"""another migrate

Revision ID: 466355067556
Revises: 710e2d81c2c4
Create Date: 2017-10-21 18:15:06.672793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '466355067556'
down_revision = '710e2d81c2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'commentsdes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('contentsrc', sa.Text(), nullable=True),
        sa.Column('contentsplit', sa.Text(), nullable=True),
        sa.Column('poscount', sa.Integer(), nullable=True),
        sa.Column('nagcount', sa.Integer(), nullable=True),
        sa.Column('emotion', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_charset='utf8')
    op.drop_table('comments_des')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'comments_des',
        sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('content_split', mysql.TEXT(), nullable=True),
        sa.Column(
            'pos_count',
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True),
        sa.Column(
            'nag_count',
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True),
        sa.Column(
            'emotion',
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True),
        sa.Column('content_src', mysql.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB')
    op.drop_table('commentsdes')
    # ### end Alembic commands ###
