"""another migrate

Revision ID: 710e2d81c2c4
Revises: 256d58e67262
Create Date: 2017-10-21 17:16:34.857551

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '710e2d81c2c4'
down_revision = '256d58e67262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments_des',
                  sa.Column('content_src', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments_des', 'content_src')
    # ### end Alembic commands ###
